name       : gajim
version    : 1.0.2
release    : 6
source     :
    - https://gajim.org/downloads/1.0/gajim-1.0.2.tar.bz2 : bc49d82001e11646e83521c2f1367a4cc5e3be54d6a9a5732f6a9e99f9f0de73
license    : GPL-3.0-only
component  : network.im
summary    : The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
description: |
    The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
rundeps    :
    - bind-utils
    - python-openssl
    - python-nbxmpp
setup      : |
build      : |
    %python3_setup
install    : |
    %python3_install
