name       : gajim
version    : 0.16.8
release    : 4
source     :
    - https://gajim.org/downloads/0.16/gajim-0.16.8.tar.bz2 : 46d4887857455b6e104d0478735edb51569bfa384578ffb4f4da81f1649b6a32
license    : GPL-3.0
component  : network.im
summary    : The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
description: |
    The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
rundeps    :
    - bind-utils
    - python-asn1
    - python-cryptography
    - python-openssl
    - python-gtk2
    - python-nbxmpp
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
