name       : gajim
version    : 1.5.2
release    : 20
source     :
    - https://gajim.org/downloads/1.5/gajim-1.5.2.tar.gz : 917a46686a7d3967436b5ab7871ee7ac3d5978a1f908a9538196f2b8d674e7ff
homepage   : https://gajim.org
license    : GPL-3.0-or-later
component  : network.im
summary    : Full featured and easy to use Jabber/XMPP client
description: |
    The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
rundeps    :
    - farstream                  # Audio/Video.
    - gstreamer-1.0-libav        # Audio/Video.
    - gstreamer-1.0-plugins-ugly # Audio/Video.
    - libgtk-3
    - python-css-parser
    - python-gssapi
    - python-keyring
    - python-nbxmpp
    - python-openssl
build      : |
    %python3_setup
install    : |
    %python3_install
