name       : gajim
version    : 1.1.3
release    : 13
source     :
    - https://gajim.org/downloads/1.1/gajim-1.1.3.tar.bz2 : 261c85444b9cc150f775a5cc5b7dea6031c8fb03f9fe6a9a81cd93d62ee3fd2f
license    : GPL-3.0-or-later
component  : network.im
summary    : The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client
description: |
    The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
rundeps    :
    - python-axolotl
    - python-cssutils
    - python-keyring
    - python-nbxmpp
    - python-precis_i18n
    - python3-cairo
build      : |
    %python3_setup
install    : |
    %python3_install
