name       : gajim
version    : 1.1.1
release    : 9
source     :
    - https://gajim.org/downloads/1.1/gajim-1.1.1.tar.gz : 819c24132c3d01c894fdde21bad88ebc9f86d7fc02d5710973a298d11657169c
license    : GPL-3.0-or-later
component  : network.im
summary    : The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client
description: |
    The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
rundeps    :
    - python-axolotl
    - python3-cairo
    - python-nbxmpp

build      : |
    %python3_setup
install    : |
    %python3_install
