name       : gajim
version    : 1.0.3
release    : 7
source     :
    - https://gajim.org/downloads/1.0/gajim-1.0.3.tar.bz2 : cb3ab63b06fa4c074a6af43947143ef197fe108cdef084884a48deec38ce4437
license    : GPL-3.0-or-later
component  : network.im
summary    : The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client
description: |
    The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
rundeps    :
    - python3-cairo
    - python-nbxmpp
build      : |
    %python3_setup
install    : |
    %python3_install
