name       : gajim
version    : 1.3.2
release    : 16
source     :
    - https://gajim.org/downloads/1.3/gajim-1.3.2.tar.gz : 70ea462b3f3c3b3c0b8d3129fae912d24062e77a8cce80781f69e8f43eda5fee
homepage   : https://gajim.org
license    : GPL-3.0-or-later
component  : network.im
summary    : Full featured and easy to use Jabber/XMPP client
description: |
    The goal of Gajim is to provide a full featured and easy to use Jabber/XMPP client.
builddeps  :
    - libgtk-3          # Tests.
    - python-css-parser # Tests.
    - python-keyring    # Tests.
    - python-nbxmpp     # Tests.
    - python-openssl    # Tests.
    - python3-cairo     # Tests.
rundeps    :
    - farstream                  # Audio/Video.
    - gstreamer-1.0-libav        # Audio/Video.
    - gstreamer-1.0-plugins-ugly # Audio/Video.
    - libgtk-3
    - python-css-parser
    - python-keyring
    - python-nbxmpp
    - python-openssl
    - python3-cairo
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-PyGIWarning.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Skipping GUI tests. solbuild has no screen.
    rm -f test/unit/test_gui_interface.py
    %python3_test
